---
- hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
  user: root
  tasks:
  - name: ensure lighttpd is at the latest version
    action: apt pkg=lighttpd state=latest
    notify:
    - restart lighttp
#  - name: write the apache config file
#    action: template src=/files/tmp/srv/httpd.j2 dest=/etc/httpd.conf
#    notify:
#    - restart apache
  - name: ensure lighttpd is running
    action: service name=lighttpd state=started
  handlers:
    - name: upgraded lighttpd
      action: service name=lighttpd state=restarted
