---
- hosts: all
  user: root
  tasks:
  - name: Copy root rsa into location
    action: copy src=/common/ansible-conf/all-remote/root/.ssh/id_rsa.deployer dest=/root/.ssh/id_rsa.deployer owner=root group=root mode=600
  - name: Copy root rsa files into location
    action: copy src=/common/ansible-conf/all-remote/root/.ssh/id_rsa.deployer.pub dest=/root/.ssh/id_rsa.deployer.pub owner=root group=root mode=600
  - name: Ensure Bitbucket compatible .ssh/config and .ssh/known_hosts are present, and correct
    action: copy src=/common/ansible-conf/all-remote/root/.ssh/config dest=/root/.ssh/config owner=root group=root mode=600
    action: copy src=/common/ansible-conf/all-remote/root/.ssh/known_hosts dest=/root/.ssh/known_hosts owner=root group=root mode=600
#    action: lineinfile dest=/root/.ssh/known_hosts create=true state=present regexp="fDQVTKJEeue78lSkGA" line="|1|gsbkaJkAwIwWcylvh5AK5KW0djk=|uLG1+fDQVTKJEeue78lSkGA/1+s= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw=="
#    action: lineinfile dest=/root/.ssh/known_hosts state=present regexp="8qdRKWlKAyEyTKJX8LK3rhS4" line="|1|jTBdrP0GijrSrkcyvrH8m3DhLWA=|mE/8qdRKWlKAyEyTKJX8LK3rhS4= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw=="
#    action: lineinfile dest=/root/.ssh/known_hosts line='' regexp='^$' state=present
  - name: install git 
    action: apt pkg=git state=installed
