# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "precise-server"

    # config.vm.forward_port 7990, 7991

    # Create a public network, which generally matched to bridged network.
    # Bridged networks make the machine appear as another physical device on
    # your network.
    # config.vm.network :public_network

    # If true, then any SSH connections made will enable agent forwarding.
    # Default value: false
    config.ssh.forward_agent = true

    # Provider-specific configuration so you can fine-tune various
    # backing providers for Vagrant. These expose provider-specific options.
    # Example for VirtualBox:
    config.vm.provider "virtualbox" do |vm|

        # Don't boot with headless mode
        vm.gui = false
        # Use VBoxManage to customize the VM. For example to change memory:
        vm.customize ["modifyvm", :id, "--memory", "1024"]
        vm.network :private_network, ip: "192.168.69.69"
        #vm.network "public_network"
        vm.share_folder("vagrant-root", "/vagrant", ".")

    end

    config.vm.synced_folder ".", "/vagrant", :disabled => true

    config.vm.provision "ansible" do |ansible|
        #ansible.raw_arguments = ['--user', 'vagrant']  
        ansible.playbook = "../playbooks/base.yml"
        ansible.sudo_user = 'root'
        ansible.sudo = true
        ansible.host_key_checking = false
        #ansible.verbose =  'vvvv'
        ansible.tags = ['dockerbox']
        #ansible.limit = [ 'dockerbox']
    end

end
