---
- hosts: tag_value_riak
  vars_files:
   - vars.yml
  serial: 1
  sudo: True
  pre_tasks:
  - name: make sure there are no transfers happening
    riak: wait_for_handoffs=600
  roles:
  - { role: basho.riak, tags: ["riak"], riak_version: "{{install_riak_version}}" } 
