---
- hosts: all
  vars_files:
   - ./vars.yml
  pre_tasks:
  - name: stat riak app.config 
    stat: path=/etc/riak/app.config
    register: etc_riak_app_config
  - name: stat riak_cs app.config 
    stat: path=/etc/riak-cs/app.config
    register: etc_riak_cs_app_config
  - name: stat stanchion 
    stat: path=/usr/sbin/stanchion 
    register: usr_sbin_stanchion
  tasks:

  - action: apt name={{item}} state=installed
    with_items:
    - libssl0.9.8
    - s3cmd
    when: ansible_lsb.id == "Ubuntu"

  - name: download stanchion
    action: get_url 
      url=http://s3.amazonaws.com/downloads.basho.com/stanchion/1.4/1.4.3/ubuntu/precise/stanchion_1.4.3-1_amd64.deb 
      sha256sum=eb4ca8ebafe8369da4f47fd714ddd9886cc31c4a942cb021203230859ce4b5e4
      dest=/tmp/stanchion.deb
    when: ansible_lsb.id == "Ubuntu" and usr_sbin_stanchion.stat.exists == false

  - name: download riak
    action: get_url 
      url=http://s3.amazonaws.com/downloads.basho.com/riak/1.4/1.4.8/ubuntu/precise/riak_1.4.8-1_amd64.deb 
      sha256sum=935846e3827bdba58c113f21596041d3f89bde3802e8833876ff009ca4235417
      dest=/tmp/riak.deb
    when: ansible_lsb.id == "Ubuntu" and etc_riak_app_config.stat.exists == false

  - name: download riak cs
    action: get_url 
      url=http://s3.amazonaws.com/downloads.basho.com/riak-cs/1.4/1.4.5/ubuntu/precise/riak-cs_1.4.5-1_amd64.deb
      sha256sum=63d033e89fbccb412792a2ffb8428a15c3fc9a8deb5b3091024fddc7237e7ccc
      dest=/tmp/riak_cs.deb
    when: ansible_lsb.id == "Ubuntu" and etc_riak_cs_app_config.stat.exists == false

  - action: template src=../../remote/riak_cs_files/etc/default/riak.j2 dest=/etc/default/riak mode=0644
  - action: template src=../../remote/riak_cs_files/etc/default/riak-cs.j2 dest=/etc/default/riak-cs mode=0644
  - action: template src=../../remote/riak_cs_files/etc/default/stanchion.j2 dest=/etc/default/stanchion mode=0644

  - action : shell /usr/bin/dpkg --install /tmp/riak.deb
    when: etc_riak_app_config.stat.exists == false
    register: install_riak 

  - action : shell /usr/bin/dpkg --install /tmp/riak_cs.deb
    when: etc_riak_cs_app_config.stat.exists == false
    register: install_riak_cs 

  - action : shell /usr/bin/dpkg --install /tmp/stanchion.deb
    when: usr_sbin_stanchion.stat.exists == false
    name: install_stanchion 