---
#- include: debian-packages.yml 
#  when: ansible_lsb.id == "Debian"
#- include: ubuntu-packages.yml  
#  when: ansible_lsb.id == "Ubuntu"
- hosts: all
  vars_files:
  - variables.yml
  pre_tasks:
  - name: check apt last update
    stat: path=/var/cache/apt
    register: apt_cache_stat
  - name: update apt if needed
    apt: update_cache=yes
    when: ansible_date_time.epoch|float - apt_cache_stat.stat.mtime > 60*60*12
  handlers:
  - name: first run was ran
    sudo: yes
    action: apt upgrade=yes update_cache=yes
  - name: installed base packages
    action: mail 
          msg="{{ansible_hostname}} installed"
          subject="Mail installed"
          to="{{keys_recipient}}"
  tasks:
  - name: add templated marker file
    action: template 
            src=../remote/etc/marker.j2
            dest=/etc/marker.ansible
    notify: first run was ran

  - name: install multiple packages
    action: apt name="{{item}}" state=installed
    with_items:
    - vim 
    - netcat 
    - ngrep
    - tcpdump 
    - zsh
    - git
    - tmux
    - python-pycurl
    - python-pip
    - ssh
    - openssh-server
    - mailutils
    when: ansible_lsb.id == "Ubuntu"
    notify:
    - installed base packages

  - name: ensure (LC_ALL) environment is correct 
    lineinfile:
        dest=/etc/environment
        line='LC_ALL="en_US.utf8"'
        regexp='.*LC_ALL=en_US.*'
        owner=root
        state=present
        insertafter=EOF
        create=True

  - name: ensure (LANG) environment is correct 
    lineinfile:
        dest=/etc/environment
        line='LANG="en_US.UTF-8"'
        regexp='.*LANG=en_US.*'
        owner=root
        state=present
        insertafter=EOF
        create=True

  - name: update the lang system
    sudo: yes
    shell: /usr/sbin/locale-gen --no-purge
    ignore_errors: True
