---
- include: debian-packages.yml 
  when: ansible_lsb.id == "Debian"
- include: ubuntu-packages.yml  
  when: ansible_lsb.id == "Ubuntu"
- hosts: all
  vars_files:
  - variables.yml
  handlers:
    - name: installed mail
      action: mail 
          msg="${ansible_hostname} installed"
          subject="Mail installed"
          to="{{keys_recipient}}"

  tasks:
  - name: add templated marker file
    action: template 
            src=../remote/etc/marker.j2
            dest=/etc/marker.ansible
  - name: ensure mail is installed 
    action: apt name=mailutils  state=installed
    notify:
    - installed mail