---
- include: debian-packages.yml 
- include: ubuntu-packages.yml  
- hosts: all
  user: root
  tasks:
  - name: add templated marker file
    action: template src=../remote/etc/marker.j2 dest=/etc/marker.ansible
  - name: ensure mail is installed 
    action: apt name=mailutils
    notify:
    - installed mail
  - name: install git 
    action: apt pkg=git state=installed  
  - name: Ensure Bitbucket compatible .ssh/known_hosts is present
    action: copy 
            src="../remote/root/.ssh/known_hosts" 
            dest="/root/.ssh/known_hosts" 
            owner=root group=root mode=600
    notify:
    - updated_ssh
  - name: Generate ssh public/private keys for the root user, if necessary.
    action: user name=root generate_ssh_key=yes ssh_key_bits=2048   
    notify:
    - generated ssh keys
  handlers:
    - name: updated_ssh
      action: mail msg='${ansible_hostname} ssh updated' subject='Ansible-report Bottle installation' to='irishjava@gmail.com' 
  handlers:
    - name: generated ssh keys
      action: mail msg='${ansible_hostname} ssh keys generated' subject='Ansible-report ssh keys generated ' to='irishjava@gmail.com'  attach="/root/.ssh/id_rsa.pub"
    - name: installed mail
      action: mail msg='${ansible_hostname} installed' subject='Ansible-report Bottle installation' to='irishjava@gmail.com' 

