---
- include: base.yml
- hosts: url-chooser
  user: root
  tasks:
  - name: install python pip
    action: apt name=python-pip
  - name: ensure bottle is at latest version
    action: pip name=bottle use_mirrors=no 
    notify:
    - installed bottle
  handlers:
    - name: installed bottle
      action: mail msg='${ansible_hostname} installed' subject='Ansible-report Bottle installation' to="{{keys_recipient}}"
#      Doesn't work
