---
- hosts: all
  user: root
  tags: 
    - dockerbox
  tasks:
  - name: install multiple packages
    action: apt name="{{item}}" state=installed
    with_items:
    - vim 
    - netcat 
    - ngrep
    - tcpdump 
    - zsh
    - git
    - tmux
    - python-pycurl
    - ssh
    - openssh-server
