---
- include: base.yml
- hosts: all
  sudo: no
  vars: 
     local_home: "{{ lookup('env','HOME') }}"
  tasks:
   - name: get value of current user
     action: debug msg="Value of ansible_env['HOME'] is {{ansible_env['HOME']}}"
   
   - name: make sure root can use SSH agent forwarding of default user
     lineinfile: dest=/etc/sudoers.d/ansible_ssh_auth_sock_changes
              state=present
              create=yes
              regexp='^Defaults env_keep.*"SSH_AUTH_SOCK"$'
              line='Defaults env_keep += "SSH_AUTH_SOCK"'
     sudo: yes

   - name: Get value of unpriv user 
     shell: /usr/bin/id -un
     sudo: no 
     register: effective_username

   - name: Get homedir of unpriv user 
     sudo: no 
     shell: "echo $HOME"
     register: effective_homedir

   - name: debug the effective_username
     action: debug var="Effective username is {{effective_username.stdout}}, homedir is {{effective_homedir.stdout}}"

   - name: Create the setup.sh file in the user homedir 
     action: template 
            src=../remote/setup.sh
            dest="{{effective_homedir.stdout}}/setup.sh"
            owner="{{effective_username.stdout}}" 
            mode=0755