---
- include: base.yml
- hosts: all
  roles:
        - binarytemple.docker
  tasks:
  - name: install sshd
    action: apt name={{item}} state=installed
    with_items:
    - ssh
    - openssh-server
  - name: copy docker project to filesystem location
    action: git repo="git@bitbucket.org:bryan_picsolve/poc_docker.git" dest="{{ansible_env['HOME']}}/poc_docker" version=master
