---
- include: base.yml
- hosts: all
  vars:
    http_port: 80
    max_clients: 200
  user: root
  tasks:
  - name: ensure lighttpd is at the latest version
    action: apt pkg=lighttpd state=latest
    notify:
    - restart lighttpd
  - name: ensure lighttpd is running
    action: service name=lighttpd state=started
  handlers:
    - name: restart lighttpd
      action: service name=lighttpd state=restarted
