---
- hosts: all
  vars_files:
   - ./riak/vars.yml
- include: riak/redhat.yml
  when: ansible_lsb.major_release == "6" and ansible_os_family == "RedHat"
- include: riak/debian.yml
  when: ansible_os_family == "Debian"
  tasks:
   # We need to add the permissive configuration files
  - action: template src=../../remote/riak_files/etc/riak/app.config.j2 dest=/etc/riak/app.config mode=0644
    register: config_change
    when: install_riak is defined

  - action: template src=../../remote/riak_files/etc/riak/vm.args.j2 dest=/etc/riak/vm.args mode=0644
    register: config_change
    when: install_riak is defined

  - name: start riak service
    action: service name=riak state=restarted
    when: config_change|changed

  - action: shell /usr/sbin/riak ping
    register: riak_result
    until: riak_result.stdout.find("pong") != -1
    retries: 5
    delay: 10
