---
- include: base.yml
- hosts: all
  user: root
  tasks:
  - name: prepare for my services installation
    action: file path=/srv mode=0755 state=directory  
    notify:
    - created srv directory
  handlers:
    - name: created srv directory
      action: mail msg='${ansible_hostname} created /srv' subject='ansible /srv created' to='irishjava@gmail.com' 
