---
- hosts: all
  sudo: yes
  tasks:
  - name: install multiple packages
    action: apt name="{{item}}" state=installed
    with_items:
    - vim 
    - netcat 
    - ngrep
    - tcpdump 
    - zsh
    - git
    - tmux
    - python-pycurl
    - ssh
    - openssh-server
    when: ansible_lsb.id == "Ubuntu"

  - name: ensure (LC_ALL) environment is correct 
    lineinfile:
        dest=/etc/environment
        line='LC_ALL="en_US.utf8"'
        regexp='.*LC_ALL=en_US.*'
        owner=root
        state=present
        insertafter=EOF
        create=True

  - name: ensure (LANG) environment is correct 
    lineinfile:
        dest=/etc/environment
        line='LANG="en_US.UTF-8"'
        regexp='.*LANG=en_US.*'
        owner=root
        state=present
        insertafter=EOF
        create=True

  - name: update the lang system
    sudo: yes
    shell: /usr/sbin/locale-gen --no-purge
    ignore_errors: True
