---
- hosts: all
  user: root
  tags: 
    - dockerbox
  tasks:
  - name: install multiple packages
    action: apt name="{{item}}" state=installed
    with_items:
    - vim 
    - netcat 
    - ngrep
    - tcpdump 
    - emacs 
    - zsh 
    - tmux
    - python-pycurl
    when: ansible_lsb.id == "Ubuntu"
  - name: ensure (LANG) environment is correct 
    lineinfile:
        dest=/etc/environment
        line='LC_ALL="en_GB.utf8"'
        regexp=".*LC_ALL.*"
        owner=root
        state=present
        insertafter=EOF
        create=True
