---
- hosts: all
  user: root
  vars:
  - is_ubuntu: "'${ansible_distribution}' == 'Ubuntu'"
  tasks:
  - name: install multiple packages
    action: apt name=$item state=installed
    with_items:
    - vim 
    - netcat 
    - ngrep
    - tcpdump 
    - emacs 
    - zsh 
    - tmux
    only_if: "$is_ubuntu"
